//DETALLES VARS
export const SET_CLAVE = 'SET_CLAVE';
export const SET_COMENTARIO = 'SET_COMENTARIO';
export const SET_ERRORS = 'SET_ERRORS';
export const AGREGAR_IMAGEN_SELECCIONADA = 'AGREGAR_IMAGEN_SELECCIONADA';
export const QUITAR_IMAGEN_SELECCIONADA = 'QUITAR_IMAGEN_SELECCIONADA';
export const ENVIAR_INFORMACION = 'ENVIAR_INFORMACION';
export const SET_INFORMACION_ENVIADA = 'SET_INFORMACION_ENVIADA';
export const GET_FECHA = 'GET_FECHA';
export const GET_HORA = 'GET_HORA';
export const PREPARE_DETAILS = 'PREPARE_DETAILS';
export const SET_DETAILS_READY = 'SET_DETAILS_READY';
export const IMAGEN_SUBIDA = 'IMAGEN_SUBIDA';
export const IMAGEN_NO_SUBIDA = 'IMAGEN_NO_SUBIDA';

//TIENDAS VARS
export const FILTER_FUNCTION = 'FILTER_FUNCTION';
export const FILTER_FUNCTION_NO_TEXT = 'FILTER_FUNCTION_NO_TEXT';
export const RENDER_TIENDAS = 'RENDER_TIENDAS';
export const SET_CURRENT_STORE = 'SET_CURRENT_STORE';

//CAMPAÑAS VARS
export const SET_CAMPS = 'SET_CAMPS';
export const SET_CURRENT_CAMP = 'SET_CURRENT_CAMP';

//LOCATION VARS
export const SET_LOCATION = 'SET_LOCATION';
export const SET_HAS_LOCATION = 'SET_HAS_LOCATION';

//CAMARA VARS
export const MOVE_IMAGE = 'MOVE_IMAGE';
export const SAVE_TO_DB = 'SAVE_TO_DB';
export const SET_LOADING = 'SET_LOADING';
export const SET_IMAGEN = 'SET_IMAGEN';
export const SET_NUMERO_FOTOS = 'SET_NUMERO_FOTOS';
export const ELIMINAR_IMAGEN = 'ELIMINAR_IMAGEN';
